apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"labels":{"backstage.io/kubernetes-id":"my-quarkus-app-2","rht-gitops.com/janus-argocd":"my-quarkus-app-2-dev-build","type":"pipeline"},"name":"my-quarkus-app-2-promote","namespace":"my-quarkus-app-2-dev"},"spec":{"params":[{"description":"The git repository used in promotion","name":"git-repo-url"},{"description":"The revision to be promoted","name":"git-revision"},{"default":"image-registry.openshift-image-registry.svc:5000/my-quarkus-app-2-dev/my-quarkus-app-2","description":"source image to promote","name":"source-image","type":"string"},{"default":"image-registry.openshift-image-registry.svc:5000/my-quarkus-app-2-preprod/my-quarkus-app-2","description":"destination image to promote to","name":"destination-image","type":"string"},{"default":"latest","name":"source-image-tag","type":"string"},{"default":"latest","name":"destination-image-tag","type":"string"},{"name":"namespace","type":"string"},{"description":"The hostname of the git instance","name":"git-host","type":"string"},{"description":"The owner of the repo","name":"git-owner","type":"string"},{"description":"The name of the component","name":"component-id","type":"string"},{"description":"Common password used in demo","name":"common-password-secret","type":"string"},{"description":"ArgoCD host","name":"argocd-host","type":"string"},{"name":"policy-configuration","type":"string"},{"name":"rekor-host","type":"string"},{"name":"tuf_mirror","type":"string"}],"tasks":[{"name":"copy-image-tag","params":[{"name":"srcImageURL","value":"docker://$(params.source-image):$(params.source-image-tag)"},{"name":"destImageURL","value":"docker://$(params.destination-image):$(params.destination-image-tag)"},{"name":"srcTLSverify","value":"false"},{"name":"destTLSverify","value":"false"}],"taskRef":{"kind":"ClusterTask","name":"skopeo-copy"},"workspaces":[{"name":"images-url","workspace":"images-url"}]},{"name":"copy-image-latest","params":[{"name":"srcImageURL","value":"docker://$(params.source-image):$(params.source-image-tag)"},{"name":"destImageURL","value":"docker://$(params.destination-image):latest"},{"name":"srcTLSverify","value":"false"},{"name":"destTLSverify","value":"false"}],"runAfter":["copy-image-tag"],"taskRef":{"kind":"ClusterTask","name":"skopeo-copy"},"workspaces":[{"name":"images-url","workspace":"images-url"}]}],"workspaces":[{"name":"images-url"}]}}
  resourceVersion: '9023775'
  name: production
  uid: 8de52032-d94b-4a1b-bf63-48af337b2916
  creationTimestamp: '2025-04-17T00:42:25Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:backstage.io/kubernetes-id': {}
            'f:rht-gitops.com/janus-argocd': {}
            'f:type': {}
        'f:spec':
          .: {}
          'f:params': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2025-04-17T00:42:25Z'
  namespace: pipeline-test
  labels:
    backstage.io/kubernetes-id: my-quarkus-app-2
    rht-gitops.com/janus-argocd: my-quarkus-app-2-dev-build
    type: pipeline
spec:
  params:
    - description: The git repository used in promotion
      name: git-repo-url
      type: string
    - description: The revision to be promoted
      name: git-revision
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/my-quarkus-app-2-dev/my-quarkus-app-2'
      description: source image to promote
      name: source-image
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/my-quarkus-app-2-preprod/my-quarkus-app-2'
      description: destination image to promote to
      name: destination-image
      type: string
    - default: latest
      name: source-image-tag
      type: string
    - default: latest
      name: destination-image-tag
      type: string
    - name: namespace
      type: string
    - description: The hostname of the git instance
      name: git-host
      type: string
    - description: The owner of the repo
      name: git-owner
      type: string
    - description: The name of the component
      name: component-id
      type: string
    - description: Common password used in demo
      name: common-password-secret
      type: string
    - description: ArgoCD host
      name: argocd-host
      type: string
    - name: policy-configuration
      type: string
    - name: rekor-host
      type: string
    - name: tuf_mirror
      type: string
  tasks:
    - name: copy-image-tag
      params:
        - name: srcImageURL
          value: 'docker://$(params.source-image):$(params.source-image-tag)'
        - name: destImageURL
          value: 'docker://$(params.destination-image):$(params.destination-image-tag)'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: images-url
    - name: copy-image-latest
      params:
        - name: srcImageURL
          value: 'docker://$(params.source-image):$(params.source-image-tag)'
        - name: destImageURL
          value: 'docker://$(params.destination-image):latest'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      runAfter:
        - copy-image-tag
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: images-url
  workspaces:
    - name: images-url
