apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: '2025-05-12T17:45:32Z'
  generation: 2
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:results': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2025-05-12T18:53:45Z'
  name: build-bootc-image
  namespace: my-quarkus-app-dev
  resourceVersion: '2098196'
  uid: b1e1684c-8836-4bb9-a8e0-3547b935d9b0
spec:
  params:
    - default: 'https://gitlab-gitlab.apps.cluster-h8p9j.h8p9j.sandbox1517.opentlc.com/development/my-quarkus-app.git'
      description: source repo that contains the application code
      name: source-repo
      type: string
    - default: bootc-builds
      description: source branch to build from
      name: source-branch
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/my-quarkus-app-dev/my-quarkus-app'
      description: reference of the image that will get created
      name: output-image
      type: string
  results:
    - description: ''
      name: IMAGE_URL
      value: $(tasks.build-image.results.IMAGE_URL)
    - description: ''
      name: IMAGE_DIGEST
      value: $(tasks.build-image.results.IMAGE_DIGEST)
    - description: ''
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: ''
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.source-repo)
        - name: revision
          value: $(params.source-branch)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-folder
    - name: package
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source-folder
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.output-image)
      runAfter:
        - package
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: source-folder
  workspaces:
    - name: source-folder
    - name: maven-settings
    - name: docker-config
    - name: reports
