apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: "2025-05-22T19:36:25Z"
  generation: 9
  labels:
    type: pipeline
  name: bootc-image-build-pipeline
  namespace: bootc-image-build
  resourceVersion: "12991725"
  uid: 48eaf53a-0488-4c8f-8eee-a1ddce4d58d9
spec:
  params:
  - default: https://gitlab-gitlab.apps.cluster-h8p9j.h8p9j.sandbox1517.opentlc.com/development/my-quarkus-app-1.git
    description: source repo that contains the application code
    name: source-repo
    type: string
  - default: bootc-builds
    description: source branch to build from
    name: source-branch
    type: string
  - default: quay-h8p9j.apps.cluster-h8p9j.h8p9j.sandbox1517.opentlc.com/quayadmin/rhel-bootc
    description: reference of the image that will get created
    name: output-image
    type: string
  results:
  - description: ""
    name: IMAGE_URL
    value: $(tasks.build-sign-image.results.IMAGE_URL)
  - description: ""
    name: IMAGE_DIGEST
    value: $(tasks.build-sign-image.results.IMAGE_DIGEST)
  - description: ""
    name: CHAINS-GIT_URL
    value: $(tasks.git-clone.results.url)
  - description: ""
    name: CHAINS-GIT_COMMIT
    value: $(tasks.git-clone.results.commit)
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.source-repo)
    - name: revision
      value: $(params.source-branch)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: source-folder
  - name: package
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: maven
    workspaces:
    - name: source
      workspace: source-folder
    - name: maven-settings
      workspace: maven-settings
  - name: build-sign-image
    params:
    - name: IMAGE
      value: $(params.output-image)
    runAfter:
    - package
    taskRef:
      params:
      - name: name
        value: buildah
      - name: namespace
        value: my-quarkus-app-1-dev
      - name: kind
        value: task
      resolver: cluster
    workspaces:
    - name: source
      workspace: source-folder
  workspaces:
  - name: source-folder
  - name: maven-settings
  - name: docker-config
  - name: reports
